tap "homebrew/cask-fonts"
brew "git"
brew "htop"
brew "nmap"
brew "prettyping"
brew "python3"
brew "tldr"
brew "tree"
brew "wget"
brew "mas"
brew "bash-completion"
brew "itermocil"


cask "alfred"
cask "adguard"
cask "appcleaner"
cask "font-ubuntu-mono-nerd-font"
cask "google-chrome"
cask "iina"
#cask "istat-menus"
cask "iterm2"
#cask "transmit"
cask "visual-studio-code"
cask "rambox"
cask "evernote"
cask "postman"
cask "docker"
cask "vnc-viewer"
cask "skype"
cask "microsoft-edge"
cask "sublime-text"
cask "itsycal"
cask "google-backup-and-sync"
cask "windscribe"
cask "keepassx"
cask "tiles"
cask "adobe-acrobat-reader"


